<?php

/**
 * @file
 * Render an administrative menu as a dropdown menu at the top of the window.
 */

// Special responses to mlid queries.
define('VMS_FRONT_PAGE',    -1);
define('VMS_MLID_MISSING',  -2);
define('VMS_BAD_CONFIG',    -3);

/**
 * Advertise the current views api version.
 */
function vms_views_api() {
  return array(
    'api' => '3',
  );
}

/**
 * Helper function to get active menu item IDs in three different ways.
 *
 * @param <string> $trail
 *   Sets if the menu trail should be included or not. Three values are
 *   recognized:
 *     * 'current_only' returns the current mlid, period. The default behaviour.
 *     * 'trail' returns the trail of mlids to the top of the menu tree, ending
 *       with the front page. Is returned on the form 1+2+3 to work with Views.
 *     * 'exclude_current' works as the 'trail' option, but excludes the
 *       currently active mlid from the list.
 * @return <type>
 *   A single mlid or a trail of mlids on the form 1+2+3.
 */
function vms_get_current_mlid($trail = 'current_only') {
  // Front page is a special case, and doesn't have any mlid. This is handled
  // separately, to allow some smoother process below.
  if (drupal_is_front_page()) {
    if ($trail == 'current_exclude') {
      return VMS_MLID_MISSING;
    }
    else {
      return VMS_FRONT_PAGE;
    }
  }

  // Get the current active menu link trail. Yes, the *set* function is also
  // used to get the active trail. It is called 'DX'.
  $menu_trail = menu_set_active_trail();

  // Note that this operation *removes* an item from the array it works with,
  // while also populating the new variable.
  $current_menu_item = array_pop(&$menu_trail);

  if (!isset($current_menu_item['mlid'])) {
    // If we don't have any active menu item, and we're NOT at the front page,
    // something is awry – we could for example be on a 404 page. Return -2 to
    // allow recognizing this special case.
    return VMS_MLID_MISSING;
  }

  // Set a fake mlid for the top item in the trail, corresponding to the front
  // page.
  $menu_trail[0]['mlid'] = VMS_FRONT_PAGE;

  // Check the different configuration cases, and return mlids accordingly.
  switch ($trail) {
    case 'current_only' : {
      return $current_menu_item['mlid'];
    }

    case 'trail' : {
      $mlids = array();
      foreach ($menu_trail as $menu_item) {
        $mlids[] = $menu_item['mlid'];
      }
      $mlids[] = $current_menu_item['mlid'];

      return implode('+', $mlids);
    }

    case 'exclude_current' : {
      $mlids = array();
      foreach ($menu_trail as $menu_item) {
        $mlids[] = $menu_item['mlid'];
      }

      return implode('+', $mlids);
    }
  }

  // If we got here, something is wrong. The $trail setting could for example
  // have an unrecognized value.
  return VMS_BAD_CONFIG;
}
